### ISSUE TITLE
When you will release the code?

### ISSUE THREAD

**Issue by xueking1** [tudelft-iv/UniBEV#1]
Thank you for your great work. 

When you will release the code of your great work??

**Comment by Shiming94** [comment]
Hi, thanks for your interest in our work. I am still doing the last check for our codes. We will release it this week, and I will let you know here.

**Comment by xueking1** [comment]
Thanks for your response, your work on multimodal 3D object detection with missing modalities is amazing. Therefore, I look forward to your work. Thank you!

**Comment by Shiming94** [comment]
Thank you so much, Yiyu! I still want to keep this issue open till I release the code so other people will know my release plan!

**Comment by Shiming94** [comment]
Hi, @xueking1, Yiyu; sorry for the delayed reply. 

Now, the main contents of our paper have been uploaded to the repo. I think the current repo is easy to use to reproduce our work. I will upload the remaining stuff in the TODO list next week. 

Thanks again for your interest in our work! Feel free to let me know if you have other questions.
 
Best,
Shiming
