### ISSUE TITLE
Training and evaluation UniBEV

### ISSUE THREAD

**Issue by tranthiha** [tudelft-iv/UniBEV#2]
Hi,

I’m really impressed with your work and appreciate you making your code available on GitHub—it’s been very helpful. I'm currently trying to train and evaluate your model using MMDetection3D, as recommended in the docs/run_eval.md, but I’m finding it a bit challenging.

If possible, could you provide more detailed instructions on how to do this? Additionally, I have to work on a Windows operating system, and I’m wondering if this is feasible.

Thank you in advance. I look forward to your response.

**Comment by Shiming94** [comment]
Hi, thanks for your interest in our work! 

May I know where errors you have met when you were trying to evaluate or train our model? After you installed the mmdetection3d framework and immigrated our codes into the project folder, you can simply run training with the training script, `train_UniBEV.py` in the `tools` folder. 

But I am not sure if the code can run perfectly in Windows as our code was fully developed under Ubuntu. Let me know if you have other questions about our code!

**Comment by tranthiha** [comment]
Apologies for the delayed response.

I've been struggling to implement MMDetection3D on Windows, and unfortunately, I still haven't resolved the issue. I'm considering whether it would be possible to use a different tool to evaluate your model instead of relying on MMDetection3D.

Thank you for your understanding.

**Comment by Shiming94** [comment]
Hi, @tranthiha; actually, the model UniBEV itself is a PyTorch-based model; it just uses the framework and a lot of tools provided by mmdetection3d. But because mmdetectio3d is a highly integrated tool, I guess it would be a little hard to use UniBEV separately. I suggest you read the documents of mmdetection3d, as they should have some solutions for deploying their model on Windows or Docker.

**Comment by tranthiha** [comment]
> Hi, @tranthiha; actually, the model UniBEV itself is a PyTorch-based model; it just uses the framework and a lot of tools provided by mmdetection3d. But because mmdetectio3d is a highly integrated tool, I guess it would be a little hard to use UniBEV separately. I suggest you read the documents of mmdetection3d, as they should have some solutions for deploying their model on Windows or Docker.

Hi, @Shiming94 
I’m currently using WSL to simulate a Linux environment on Windows. I’ve successfully installed MMDetection3D, but I encountered the following error:
(dl_env_py38) ha@DESKTOP-B4UP57B:/mnt/g/Ha/nuscenes/det_tool/mmdetection3d$ python tools/test_UniBEV.py /mnt/g/Ha/nuscenes/UniBEV/projects/UniBEV/configs/unibev/unibev_nus_LC_cnw_256_modality_dropout.py /mnt/g/Ha/nuscenes/det_tool/mmdetection3d/checkpoints/unibev_cnw_256_nus_MD.pth --eval mAP NDS
/mnt/g/Ha/dl_env_py38/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
mmdet3d.unibev_plugin
load checkpoint from local path: /mnt/g/Ha/nuscenes/det_tool/mmdetection3d/checkpoints/unibev_cnw_256_nus_MD.pth
2024-09-10 11:40:49,828 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.0.conv2 is upgraded to version 2.
2024-09-10 11:40:49,831 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.1.conv2 is upgraded to version 2.
2024-09-10 11:40:49,833 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.2.conv2 is upgraded to version 2.
2024-09-10 11:40:49,835 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.3.conv2 is upgraded to version 2.
2024-09-10 11:40:49,838 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.4.conv2 is upgraded to version 2.
2024-09-10 11:40:49,840 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.5.conv2 is upgraded to version 2.
2024-09-10 11:40:49,842 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.6.conv2 is upgraded to version 2.
2024-09-10 11:40:49,844 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.7.conv2 is upgraded to version 2.
2024-09-10 11:40:49,845 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.8.conv2 is upgraded to version 2.
2024-09-10 11:40:49,847 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.9.conv2 is upgraded to version 2.
2024-09-10 11:40:49,849 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.10.conv2 is upgraded to version 2.
2024-09-10 11:40:49,851 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.11.conv2 is upgraded to version 2.
2024-09-10 11:40:49,853 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.12.conv2 is upgraded to version 2.
2024-09-10 11:40:49,855 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.13.conv2 is upgraded to version 2.
2024-09-10 11:40:49,856 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.14.conv2 is upgraded to version 2.
2024-09-10 11:40:49,858 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.15.conv2 is upgraded to version 2.
2024-09-10 11:40:49,860 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.16.conv2 is upgraded to version 2.
2024-09-10 11:40:49,862 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.17.conv2 is upgraded to version 2.
2024-09-10 11:40:49,864 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.18.conv2 is upgraded to version 2.
2024-09-10 11:40:49,866 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.19.conv2 is upgraded to version 2.
2024-09-10 11:40:49,868 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.20.conv2 is upgraded to version 2.
2024-09-10 11:40:49,870 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.21.conv2 is upgraded to version 2.
2024-09-10 11:40:49,873 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.22.conv2 is upgraded to version 2.
2024-09-10 11:40:49,876 - root - INFO - ModulatedDeformConvPack img_backbone.layer4.0.conv2 is upgraded to version 2.
2024-09-10 11:40:49,879 - root - INFO - ModulatedDeformConvPack img_backbone.layer4.1.conv2 is upgraded to version 2.
2024-09-10 11:40:49,882 - root - INFO - ModulatedDeformConvPack img_backbone.layer4.2.conv2 is upgraded to version 2.
[                                                  ] 0/6019, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test_UniBEV.py", line 249, in <module>
    main()
  File "tools/test_UniBEV.py", line 217, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/mnt/g/Ha/nuscenes/det_tool/mmdetection3d/mmdet3d/apis/test.py", line 40, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/mnt/g/Ha/dl_env_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/g/Ha/dl_env_py38/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 51, in forward
    return super().forward(*inputs, **kwargs)
  File "/mnt/g/Ha/dl_env_py38/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/mnt/g/Ha/dl_env_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/g/Ha/nuscenes/det_tool/mmdetection3d/mmdet3d/unibev_plugin/models/detectors/unibev_detector.py", line 221, in forward
    return self.forward_test(**kwargs)
  File "/mnt/g/Ha/nuscenes/det_tool/mmdetection3d/mmdet3d/unibev_plugin/models/detectors/unibev_detector.py", line 313, in forward_test
    bbox_results, bev_embeds = self.simple_test(
  File "/mnt/g/Ha/nuscenes/det_tool/mmdetection3d/mmdet3d/unibev_plugin/models/detectors/unibev_detector.py", line 319, in simple_test
    img_feats, lidar_feats, radar_feats = self.extract_feat(img=img, points=points, radar_points=radar, img_metas=img_metas)
  File "/mnt/g/Ha/nuscenes/det_tool/mmdetection3d/mmdet3d/unibev_plugin/models/detectors/unibev_detector.py", line 146, in extract_feat
    pts_feats = self.extract_pts_feat(points) if self.use_lidar else None
  File "/mnt/g/Ha/nuscenes/det_tool/mmdetection3d/mmdet3d/unibev_plugin/models/detectors/unibev_detector.py", line 120, in extract_pts_feat
    x = self.pts_middle_encoder(voxel_features, coors, batch_size)
  File "/mnt/g/Ha/dl_env_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/g/Ha/dl_env_py38/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/g/Ha/nuscenes/det_tool/mmdetection3d/mmdet3d/models/middle_encoders/sparse_encoder.py", line 123, in forward
    x = self.conv_input(input_sp_tensor)
  File "/mnt/g/Ha/dl_env_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/g/Ha/dl_env_py38/lib/python3.8/site-packages/mmcv/ops/sparse_modules.py", line 134, in forward
    input = module(input)
  File "/mnt/g/Ha/dl_env_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/g/Ha/dl_env_py38/lib/python3.8/site-packages/mmcv/ops/sparse_conv.py", line 157, in forward
    outids, indice_pairs, indice_pair_num = ops.get_indice_pairs(
  File "/mnt/g/Ha/dl_env_py38/lib/python3.8/site-packages/mmcv/ops/sparse_ops.py", line 99, in get_indice_pairs
    return get_indice_pairs_func(indices, batch_size, out_shape,
RuntimeError: /tmp/mmcv/mmcv/ops/csrc/pytorch/cuda/sparse_indice.cu 126
cuda execution failed with error 2

The error appears related to CUDA execution failure, and I’ve already reduced samples_per_gpu to 1 to ensure the issue isn’t caused by out-of-memory problems. Here are my system details from running nvidia-smi and collect_env.py:

(dl_env_py38) ha@DESKTOP-B4UP57B:/mnt/g/Ha/nuscenes/det_tool/mmdetection3d$ nvidia-smi
Tue Sep 10 11:42:45 2024
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.39.01    Driver Version: 511.23       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:17:00.0  On |                  N/A |
|  0%   38C    P8    12W / 340W |   1645MiB / 10240MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A        26      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+

/mnt/g/Ha/dl_env_py38/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
sys.platform: linux
Python: 3.8.10 (default, Jul 29 2024, 17:02:10) [GCC 9.4.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3080
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.6, V11.6.55
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
PyTorch: 1.12.0+cu116
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.13.0+cu116
OpenCV: 4.10.0
MMCV: 1.7.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.6
MMDetection: 2.28.0
MMSegmentation: 0.30.0
MMDetection3D: 1.0.0rc6+47285b3
spconv2.0: False

Despite adjusting memory settings, the error persists. Are you familiar with this issue or have any suggestions for resolving it? Your help would be greatly appreciated.
Thank you in advance.

**Comment by Shiming94** [comment]
Hi, I just googled this error, it seems a pretty common error because of the limited GPU memory, too big batch size or mismatch of environment.

https://github.com/open-mmlab/mmdetection3d/issues/2677

https://github.com/open-mmlab/mmdetection3d/issues/21

**Comment by tranthiha** [comment]
> Hi, I just googled this error, it seems a pretty common error because of the limited GPU memory, too big batch size or mismatch of environment.
> 
> [open-mmlab/mmdetection3d#2677](https://github.com/open-mmlab/mmdetection3d/issues/2677)
> 
> [open-mmlab/mmdetection3d#21](https://github.com/open-mmlab/mmdetection3d/issues/21)

Thank you so much for your quick response. I believe the issue may be due to a lack of memory, as my computer only has one NVIDIA GeForce RTX 3080 with 10GB of VRAM. When I run the model using only LiDAR input, it runs successfully (and it took 9.6/10). Additionally, I have three questions and would greatly appreciate your help with them:

1.When I run the file unibev_nus_L.py to obtain the two metric values, mAP and NDS, I receive the following log:
(dl_env_py38) ha@DESKTOP-B4UP57B:/mnt/g/Ha/nuscenes/det_tool/mmdetection3d$ python tools/test_UniBEV.py /mnt/g/Ha/nuscenes/det_tool/mmdetection3d/projects/UniBEV/configs/unibev/unibev_nus_L.py /mnt/g/Ha/nuscenes/det_tool/mmdetection3d/checkpoints/unibev_L.pth --eval mAP NDS
/mnt/g/Ha/nuscenes/det_tool/mmdetection3d/mmcv/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
mmdet3d.unibev_plugin
load checkpoint from local path: /mnt/g/Ha/nuscenes/det_tool/mmdetection3d/checkpoints/unibev_L.pth
[                                                  ] 0/6019, elapsed: 0s, ETA:/mnt/g/Ha/dl_env_py38/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/mnt/g/Ha/nuscenes/det_tool/mmdetection3d/mmdet3d/unibev_plugin/core/bbox/coders/nms_free_coder.py:57: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  bbox_index = indexs // self.num_classes
[                                                  ] 1/6019, 0.1 task/s, elapsed: 13s, ETA: 80864s/mnt/g/Ha/nuscenes/det_tool/mmdetection3d/mmdet3d/unibev_plugin/core/bbox/coders/nms_free_coder.py:76: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.post_center_range = torch.tensor(
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6019/6019, 3.9 task/s, elapsed: 1562s, ETA:     0s
Formating bboxes of pts_bbox
Start to convert detection format...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6019/6019, 18.8 task/s, elapsed: 319s, ETA:     0s
Results writes to /tmp/tmp1knbesag/results/pts_bbox/results_nusc.json

Evaluating bboxes of pts_bbox
mAP: 0.5778
mATE: 0.3221
mASE: 0.7127
mAOE: 1.5545
mAVE: 0.2877
mAAE: 0.1797
NDS: 0.5387
Eval time: 169.4s

Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.841   0.183   0.750   1.563   0.247   0.204
truck   0.510   0.365   0.794   1.589   0.239   0.231
bus     0.657   0.354   0.862   1.568   0.629   0.186
trailer 0.392   0.597   0.865   1.571   0.202   0.143
construction_vehicle    0.183   0.698   0.695   1.619   0.123   0.316
pedestrian      0.817   0.163   0.339   1.571   0.225   0.099
motorcycle      0.635   0.229   0.790   1.536   0.414   0.253
bicycle 0.469   0.181   0.812   1.677   0.223   0.006
traffic_cone    0.665   0.169   0.335   nan     nan     nan
barrier 0.609   0.284   0.885   1.296   nan     nan
{'pts_bbox_NuScenes/car_AP_dist_0.5': 0.7437, 'pts_bbox_NuScenes/car_AP_dist_1.0': 0.8445, 'pts_bbox_NuScenes/car_AP_dist_2.0': 0.8806, 'pts_bbox_NuScenes/car_AP_dist_4.0': 0.8969, 'pts_bbox_NuScenes/car_trans_err': 0.183, 'pts_bbox_NuScenes/car_scale_err': 0.7504, 'pts_bbox_NuScenes/car_orient_err': 1.5634, 'pts_bbox_NuScenes/car_vel_err': 0.2471, 'pts_bbox_NuScenes/car_attr_err': 0.2043, 'pts_bbox_NuScenes/mATE': 0.3221, 'pts_bbox_NuScenes/mASE': 0.7127, 'pts_bbox_NuScenes/mAOE': 1.5545, 'pts_bbox_NuScenes/mAVE': 0.2877, 'pts_bbox_NuScenes/mAAE': 0.1797, 'pts_bbox_NuScenes/truck_AP_dist_0.5': 0.3112, 'pts_bbox_NuScenes/truck_AP_dist_1.0': 0.4972, 'pts_bbox_NuScenes/truck_AP_dist_2.0': 0.5951, 'pts_bbox_NuScenes/truck_AP_dist_4.0': 0.6384, 'pts_bbox_NuScenes/truck_trans_err': 0.3653, 'pts_bbox_NuScenes/truck_scale_err': 0.7941, 'pts_bbox_NuScenes/truck_orient_err': 1.5886, 'pts_bbox_NuScenes/truck_vel_err': 0.2389, 'pts_bbox_NuScenes/truck_attr_err': 0.2307, 'pts_bbox_NuScenes/trailer_AP_dist_0.5': 0.0859, 'pts_bbox_NuScenes/trailer_AP_dist_1.0': 0.3216, 'pts_bbox_NuScenes/trailer_AP_dist_2.0': 0.5355, 'pts_bbox_NuScenes/trailer_AP_dist_4.0': 0.6254, 'pts_bbox_NuScenes/trailer_trans_err': 0.5968, 'pts_bbox_NuScenes/trailer_scale_err': 0.8649, 'pts_bbox_NuScenes/trailer_orient_err': 1.571, 'pts_bbox_NuScenes/trailer_vel_err': 0.2022, 'pts_bbox_NuScenes/trailer_attr_err': 0.143, 'pts_bbox_NuScenes/bus_AP_dist_0.5': 0.4191, 'pts_bbox_NuScenes/bus_AP_dist_1.0': 0.6445, 'pts_bbox_NuScenes/bus_AP_dist_2.0': 0.7636, 'pts_bbox_NuScenes/bus_AP_dist_4.0': 0.7994, 'pts_bbox_NuScenes/bus_trans_err': 0.3535, 'pts_bbox_NuScenes/bus_scale_err': 0.8619, 'pts_bbox_NuScenes/bus_orient_err': 1.5679, 'pts_bbox_NuScenes/bus_vel_err': 0.6287, 'pts_bbox_NuScenes/bus_attr_err': 0.1858, 'pts_bbox_NuScenes/construction_vehicle_AP_dist_0.5': 0.0177, 'pts_bbox_NuScenes/construction_vehicle_AP_dist_1.0': 0.1225, 'pts_bbox_NuScenes/construction_vehicle_AP_dist_2.0': 0.255, 'pts_bbox_NuScenes/construction_vehicle_AP_dist_4.0': 0.3372, 'pts_bbox_NuScenes/construction_vehicle_trans_err': 0.6976, 'pts_bbox_NuScenes/construction_vehicle_scale_err': 0.6948, 'pts_bbox_NuScenes/construction_vehicle_orient_err': 1.6193, 'pts_bbox_NuScenes/construction_vehicle_vel_err': 0.1233, 'pts_bbox_NuScenes/construction_vehicle_attr_err': 0.3164, 'pts_bbox_NuScenes/bicycle_AP_dist_0.5': 0.4395, 'pts_bbox_NuScenes/bicycle_AP_dist_1.0': 0.4754, 'pts_bbox_NuScenes/bicycle_AP_dist_2.0': 0.4776, 'pts_bbox_NuScenes/bicycle_AP_dist_4.0': 0.4823, 'pts_bbox_NuScenes/bicycle_trans_err': 0.1807, 'pts_bbox_NuScenes/bicycle_scale_err': 0.8125, 'pts_bbox_NuScenes/bicycle_orient_err': 1.6767, 'pts_bbox_NuScenes/bicycle_vel_err': 0.223, 'pts_bbox_NuScenes/bicycle_attr_err': 0.0057, 'pts_bbox_NuScenes/motorcycle_AP_dist_0.5': 0.531, 'pts_bbox_NuScenes/motorcycle_AP_dist_1.0': 0.6412, 'pts_bbox_NuScenes/motorcycle_AP_dist_2.0': 0.677, 'pts_bbox_NuScenes/motorcycle_AP_dist_4.0': 0.6899, 'pts_bbox_NuScenes/motorcycle_trans_err': 0.2293, 'pts_bbox_NuScenes/motorcycle_scale_err': 0.7903, 'pts_bbox_NuScenes/motorcycle_orient_err': 1.5363, 'pts_bbox_NuScenes/motorcycle_vel_err': 0.4141, 'pts_bbox_NuScenes/motorcycle_attr_err': 0.2528, 'pts_bbox_NuScenes/pedestrian_AP_dist_0.5': 0.7684, 'pts_bbox_NuScenes/pedestrian_AP_dist_1.0': 0.8094, 'pts_bbox_NuScenes/pedestrian_AP_dist_2.0': 0.8346, 'pts_bbox_NuScenes/pedestrian_AP_dist_4.0': 0.8549, 'pts_bbox_NuScenes/pedestrian_trans_err': 0.1626, 'pts_bbox_NuScenes/pedestrian_scale_err': 0.3387, 'pts_bbox_NuScenes/pedestrian_orient_err': 1.5712, 'pts_bbox_NuScenes/pedestrian_vel_err': 0.2247, 'pts_bbox_NuScenes/pedestrian_attr_err': 0.0987, 'pts_bbox_NuScenes/traffic_cone_AP_dist_0.5': 0.6018, 'pts_bbox_NuScenes/traffic_cone_AP_dist_1.0': 0.6441, 'pts_bbox_NuScenes/traffic_cone_AP_dist_2.0': 0.6827, 'pts_bbox_NuScenes/traffic_cone_AP_dist_4.0': 0.7308, 'pts_bbox_NuScenes/traffic_cone_trans_err': 0.1687, 'pts_bbox_NuScenes/traffic_cone_scale_err': 0.335, 'pts_bbox_NuScenes/traffic_cone_orient_err': nan, 'pts_bbox_NuScenes/traffic_cone_vel_err': nan, 'pts_bbox_NuScenes/traffic_cone_attr_err': nan, 'pts_bbox_NuScenes/barrier_AP_dist_0.5': 0.484, 'pts_bbox_NuScenes/barrier_AP_dist_1.0': 0.5978, 'pts_bbox_NuScenes/barrier_AP_dist_2.0': 0.6627, 'pts_bbox_NuScenes/barrier_AP_dist_4.0': 0.6907, 'pts_bbox_NuScenes/barrier_trans_err': 0.2838, 'pts_bbox_NuScenes/barrier_scale_err': 0.8847, 'pts_bbox_NuScenes/barrier_orient_err': 1.2957, 'pts_bbox_NuScenes/barrier_vel_err': nan, 'pts_bbox_NuScenes/barrier_attr_err': nan, 'pts_bbox_NuScenes/NDS': 0.5386566484203265, 'pts_bbox_NuScenes/mAP': 0.5777692002541709}

=> However, while the mAP value matches what was reported in your paper (57.8%), the NDS value in my log is 53.9%, which differs from the 65.2% stated in the paper. I used the corresponding checkpoint file from the link you recommended: https://surfdrive.surf.nl/files/index.php/s/H8cWVN8Htdhg7zC, as described in the README.md. Could you please clarify what might be causing this discrepancy?

2. When I tried running unibev_nus_C.py, I encountered an issue where MSDeformableAttention3DUniQueryImg is not defined in the code. Do I need to install another package to resolve this?

3. I noticed that you used the mini_nuscenes_infos_train.pkl file for training. However, when I used create_data.py from the mmdetection3d repository, I was only able to generate files like nuscenes_infos_val.pkl. Could you please guide me on how to generate the mini_nuscenes_infos_train.pkl file for the training phase?

Once again, thank you so much for your kind support. I greatly appreciate your help.

**Comment by Shiming94** [comment]
hi Congrats!
1. for your first question, I think you used the new version of the data to create a script from mmdetection3d; what I used in this repo is still the old version; the main difference is the different definition of the yaw angle in the ground truth.
https://github.com/open-mmlab/mmdetection3d/commit/398c02ee07a5cb11cd8c737adfda92a5b287325f
2. It is weird, I will check it later, it should already exist in the code base.
3. you can simply define the version of the dataset in `create_data.py` and then rename it as `mini_nuscenes_infos_train.pkl`, but please notice, to train the network, I am not using the `mini-nuscene`; it is only used to test the completeness of code. I will fix it later.

**Comment by tranthiha** [comment]
> hi Congrats!
> 
>     1. for your first question, I think you used the new version of the data to create a script from mmdetection3d; what I used in this repo is still the old version; the main difference is the different definition of the yaw angle in the ground truth.
>        [open-mmlab/mmdetection3d@398c02e](https://github.com/open-mmlab/mmdetection3d/commit/398c02ee07a5cb11cd8c737adfda92a5b287325f)
> 
>     2. It is weird, I will check it later, it should already exist in the code base.
> 
>     3. you can simply define the version of the dataset in `create_data.py` and then rename it as `mini_nuscenes_infos_train.pkl`, but please notice, to train the network, I am not using the `mini-nuscene`; it is only used to test the completeness of code. I will fix it later.

Hi,
1. About your third point: Do you mean that after generating the nuscenes_infos_train.pth file by running tools/create_data.py with the NuScenes v1.0-trainval dataset, you then renamed it to mini_nuscenes_infos_train.pth?

2. I also tried training the UniBEV model and noticed that the load_from variable is set as:
  load_from = 'remote_checkpoints/focos_3d_r101_centerpoint.pth'.
However, I couldn’t find any instructions in the project documentation about how to obtain the file focos_3d_r101_centerpoint.pth. Could you please let me know where I can download it?

Thank you so much for your quick response! I'm working under tight deadlines for my thesis, and your prompt replies are really helpful.

**Comment by Shiming94** [comment]
no, pass the parameters when you are running the `create_data.py`, specify the version is `v1.0-mini`, you can read their code of `create-data.py` for more information.

I also uploaded the pretrained weight, please check here https://surfdrive.surf.nl/files/index.php/s/DYgjX6RWyVkawul.

**Comment by tranthiha** [comment]
Hi,

1. From the link, I received a file called resnet101_centerpoint_pretrained.py, which seems different from focos_3d_r101_centerpoint.pth. Is it still the correct file?
2. I tried training with unibev_nus_L.py, but I encountered a runtime error due to memory, as it needed 40 MiB more. I had already set samples_per_gpu = 1 and batch_size = 1, but the memory issue persisted. Do you have any suggestions on how to resolve this?
3. Have you reviewed the code that was mentioned in the second point of your previous comment?

> hi Congrats!
> 
>     1. for your first question, I think you used the new version of the data to create a script from mmdetection3d; what I used in this repo is still the old version; the main difference is the different definition of the yaw angle in the ground truth.
>        [open-mmlab/mmdetection3d@398c02e](https://github.com/open-mmlab/mmdetection3d/commit/398c02ee07a5cb11cd8c737adfda92a5b287325f)
> 
>     2. It is weird, I will check it later, it should already exist in the code base.
> 
>     3. you can simply define the version of the dataset in `create_data.py` and then rename it as `mini_nuscenes_infos_train.pkl`, but please notice, to train the network, I am not using the `mini-nuscene`; it is only used to test the completeness of code. I will fix it later.

**Comment by Shiming94** [comment]
Hi, 
1. Yes, the files only differ in their names.
2. Apologies, but this model does require a substantial amount of memory for training. To fit within your GPU constraints, you can try reducing the feature dimensions (`_dim_`), the BEV size (`bev_h_`/`bev_w_`), or even the number of encoder layers (`_encoder_layers_`). However, this might come at the cost of performance.
3. I believe I used an outdated module name. You can replace `MSDeformableAttention3DUniQueryImg` in `unibev_nus_C.py` with `MSDeformableAttention3DImg`, which is available in the repository. I'll push a corrected version of the module name soon.

**Comment by Shiming94** [comment]
Hey, I will close this issue. Should you have further questions, you can either reopen it or open a new issue.
